version: '3.1'


volumes:
  db_data:
  pgadmin_data:


services:
  postgres:
    container_name: hrf_universe_postgres
    image: postgres:13.4
    shm_size: 1g
    restart: unless-stopped
    volumes:
      - "db_data:/var/lib/postgresql/data"
      - "./migrations/data:/tmp/data"
    env_file:
      - .env
    ports:
      - "0.0.0.0:5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - "pgadmin_data:/var/list/pgadmin"
    env_file:
      - .env
    environment:
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "0.0.0.0:8080:80"
    depends_on:
      - postgres

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
